name: "hello action"
description: "action test"
inputs:
  appId:
    required: true
    description: "customize app"
    default: "appno-123"
  apiSecretKey:
    required: true
    description: 'secret key by action caller'
outputs:
  time:
    description: "get time"
runs: 
  using: 'node16'
  main: 'index.js'