name: "hello action"
description: "action test"
inputs:
  appId:
    required: true
    description: "customize app"
    default: "appno-123"
outputs:
  time:
    description: "get time"
runs: 
  using: 'node16'
  main: 'dist/index.js'