name: "hello action"
description: "action test"
inputs:
  appId:
    required: true
    description: "customize app"
    default: "appno-123"
  apiSecretKey:
    required: true
    description: 'secret key by action caller'
  artifact:
    required: true
    description: 'artifact file'
  accessKeyId: 
    required: true
    description: '验证使用，正式 action 将删除'
  accessKeySecret:
    required: true
    description: '验证使用，正式 action 将删除'
  sts: 
    required: true
    description: '验证使用，正式 action 将删除'
  githubToken:
    required: true
    desc
outputs:
  time:
    description: "get time"
runs: 
  using: 'node16'
  main: 'dist/index.js'
